package plugins.danyfel80.histogram3d;

import plugins.adufour.ezplug.EzPlug;
import icy.gui.dialog.MessageDialog;

public class Histogram3D extends EzPlug {

	@Override
	protected void initialize() {
		// TODO Auto-generated by Icy4Eclipse
	}

	@Override
	protected void execute() {
		// TODO Auto-generated by Icy4Eclipse
		MessageDialog.showDialog("Histogram 3D is working fine !");
	}

	@Override
	public void clean() {
		// TODO Auto-generated by Icy4Eclipse
	}
}
